### ISSUE TITLE
Multiple errors with simple config 

### ISSUE THREAD

**Issue by DragonReach** [PlagueHO/LabBuilder#1]
Used the Forest Root and DHCP sample as a starting point, seems documentation is lacking and you start from the assumption of VMs running to pull the template VHDs from.  I have sysprepped images and see multiple errors that aren't helpful.  Example below. -- I have no idea what to put in the XML for this value as there is no sample that uses it and a cursory view of the code doesn't provide any real enlightenment 

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At D:\HVFCLab\LabBuilder.psm1:456 char:31
+     If (-not (Test-Path -Path $FullConfigPath))
+                               ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand

in addition this error makes no sense to me - 
Get-LabVMTemplates : The Template Source VHD 'Template Windows Server 2016 Datacenter Full' in Template
'Win2016-DataCenterFULLG2.VHDX' could not be found.
At D:\HVFCLab\LabBuilder2.psm1:4341 char:20
+     $VMTemplates = Get-LabVMTemplates `
+                    ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-LabVMTemplates], InvalidOperationException
    + FullyQualifiedErrorId : TemplateSourceVHDNotFoundError,Get-LabVMTemplates

It seems to be putting the wrong value - when I tried to introduce a pause it never showed in enumerating the templates. 

A sample XML that you actually use and an idea of the existing environment it is based on would help.  This is a really cool idea and I would love to get use out of it.  Sorry if this is something simple that I am overlooking

**Comment by DragonReach** [comment]
Ok, I have resolved these so far -  FullConfigPath fails if config path is not a relative path since you are building the FullConfigPath from it.  Templates issue was resolved because of a typo on my part and the file didn't exist.  - now working on finding out why unattend.xml didn't inject

**Comment by PlagueHO** [comment]
Hi @DragonReach,

I actually had no idea anyone was keeping an eye on this repo :smile:

I'm in the process of reworking a bit of the code on this and trying to get 100% unit test code coverage on it. However, it should work - mostly (there are some certificate issues with PS build 10586). But any feed back, error reports or general suggestions are very much appreciated. Progress on this has been a bit slow lately because I've been spending a lot of time trying to complete the DSC resources that the repo uses (DFS, iSCSI, FSRM etc) and get them into the MS Community resources collection. But they're all pretty much completed now so I'll be able to give this project some more attention.

You're 100% right - the documentation is very much incomplete, but I'll get onto that first thing next week as it might help with a few of your issues/questions.

Feel free to paste a copy of your config here and I'll see if I can figure out what is up and/or improve my error messages.

Are you running the Install-Lab with the -Verbose parameter? This should give a little bit more information about what is going on.

Anyway, I'll get onto this first thing next week and see if I can't resolve a few of these issues for you.

Thanks again for using this project :smile: it is good to know someone else might find it useful!

**Comment by DragonReach** [comment]
I just found this the other day quite by accident, and in reality I was working on a similar project for creating lab environments for my students. I was using your other script to create nano server VHDs and got curious about this and saw you were doing the same as I.

Unattend.xml didn't inject in my builds because I am not building from a sysprepped image, but rather VHDX files created from Convert-WindowsImage - panther path doesn't exist.   Simple fix by adding a new-item -type directory with -force to resolve, I also removed the product key section on mine from the unattend to prevent that stalling the OS setup.

Also since my test box is running Win10 on the insider fast ring it is entirely possible for me to have issues due to that. I think currently I am on build 14257 

I may move everything over to a Win 2016 TP4 box as long as I and use RDP to get to it.  I just travel too much.

I'll be hammering this pretty much for the next few weeks till I can get the functionality I need so I'll try to provide feedback in a timely fashion and will provide you with any changes I make that I think will be useful rather than tweaks for different environment.

**Comment by DragonReach** [comment]
Issues 

Unable to setup new-pssession due to untrusted host.

Have to had new VM into trusted host. - added code  - In addition set credentials to include OS Name in Function Wait-LabVMInit 

Actual fix 
```

$Username = $VM.ComputerName + '\Administrator'
	Write-Verbose $Username
    [PSCredential] $AdmininistratorCredential = New-Credential `
        -Username $Username `
        -Password $VM.AdministratorPassword
```

propagated this to every instance that was used to create credentials for a PSSession


```

if (!((Get-Item WSMAN::localhost\Client\TrustedHosts) -eq "$IPAddress")) {set-item WSMAN::localhost\Client\TrustedHosts "$IPAddress" -Force}
                Write-Verbose "Included $IPAddress in TrustedHosts"
	     Write-Verbose "Connecting to $IPAddress with $AdminCredential"

```

Setup.cmd has no line breaks and so processes as a single line

Added Carriage returns and a timeout to deal with some sort of timing issue that was preventing initial setup to not return and PS1 to not run.
```

    # Write out the CMD Setup Complete File
    $SetupCompleteCmd = @"
@echo SetupComplete.cmd Script Started... >> %SYSTEMROOT%\Setup\Scripts\SetupComplete.log `r
Timeout 30 `r
powerShell.exe -ExecutionPolicy Unrestricted -Command `"%SYSTEMROOT%\Setup\Scripts\SetupComplete.ps1`" `r
@echo SetupComplete.cmd Script Finished... >> %SYSTEMROOT%\Setup\Scripts\SetupComplete.log `r
@echo Initial Setup Completed - this file indicates that setup has completed. >> %SYSTEMROOT%\Setup\Scripts\InitialSetupCompleted.txt`r
"@
    $null = Set-Content `
        -Path (Join-Path -Path $VMLabBuilderFiles -ChildPath 'SetupComplete.cmd') `
        -Value $SetupCompleteCmd -Force -Encoding Ascii

```
Minor textual fix  -- previously the variable was $MemortStartupBytes 

```
        # Get the Template Default Startup Bytes
        [Int64] $MemoryStartupBytes = 0
        If ($Template.MemoryStartupBytes)
        {
            $MemoryStartupBytes = (Invoke-Expression $Template.MemoryStartupBytes)
        } # If


```
Changed mount point from env:temp to under lab build environment when troubleshooting
```

    # Mount the VMs Boot VHD so that files can be loaded into it
    Write-Verbose -Message $($LocalizedData.MountingVMBootDiskMessage `
        -f $VM.Name,$VMBootDiskPath)
    [String] $MountPoint = Join-Path `
        -Path $VMLabBuilderFiles `
        -ChildPath 'Mount'
    $null = New-Item -Path $MountPoint -ItemType Directory
    $null = Mount-WindowsImage -ImagePath $VMBootDiskPath -Path $MountPoint -Index 1

```

Added line to ensure unattend.xml directory "Panther" exists
```
    # Apply an unattended setup file
    Write-Verbose -Message $($LocalizedData.ApplyingVMBootDiskFileMessage `
        -f $VM.Name,'Unattend','Unattend.xml')
	New-Item -Type Directory $MountPoint\Windows\Panther -Force 
    $null = Copy-Item `
        -Path (Join-Path -Path $VMLabBuilderFiles -ChildPath 'Unattend.xml') `
        -Destination "$MountPoint\Windows\Panther\Unattend.xml" `
        -Force
```



Removed extraneous entries for setupcompleteps file 


Renamed $AdmininistratorCredential to $AdminCredential to correct typo and ease reading


While loops are not timing out -- have run at times over 15 minutes - haven't tried to fix yet. 

Had to use -moduleversion and specify current module of DSC resource module due to what appears to be a bug with powershell but I will have to repro on a clean box.

`Example for xNetworking - Import-DscResource -ModuleName "xNetworking" -ModuleVersion 2.7.0.0 `


In addition to this I will be extending things a bit as I need more than a single data disk added to VMs

I'm new to the whole github thing, so if I need to be doing things differently let me know.``

**Comment by PlagueHO** [comment]
Some awesome ideas, changes and fixes there. Thank you!  I'll take a propper look and incorporate them into the master branch when I get home. I'm out of town till tonight.



Re: the dsc module version issue, I wrote a blog post on this a month or so back. I ran into this issue and several others relating to dsc credential encryption when 10586 was released. But that is still good detective work on the solution - took me quite a while to figure it out.

**Comment by DragonReach** [comment]
Found another minor item, your Regex expression can’t handle a hyphen – and the hyper-v DSC modules fail to load.  So I’ll be learning Regex here after dinner ☺

**Comment by PlagueHO** [comment]
I've begun work on this again now and pushed the first fix through into Dev (the Regex one).

I'll create individual issue's for each of the changes in this and address them with individual PR's to the dev branch and let you know when they're through.

I'm working on the documentation and unit tests at the same time so it take a bit longer than I'd like.

Thanks again for your help and feedback on this.

**Comment by DragonReach** [comment]
Glad to help make things better.

Although I am a total newbie when it comes to the GitHub stuff so not real good at proper submissions – Always been more of tech support/admin than dev.

**Comment by PlagueHO** [comment]
Not a problem - everyone has been new to this at some point :smile:

I usually follow the process I learned when submitting to the MSFT DSC community resources:
1. Create a new issue on the repo.
2. Create a branch on your local fork of the Repo (usually with the Issue number of the new issue). E.g.
```
git checkout -b "Issue-999-Fix-Some-Bug-Add-A-Feature"
```
3. Make the changes to your branch
4. Submit the branch to the upstream (e.g. this repo) using a Pull Request
_in the title of the PR end it with "Fixes #999" because then when I merge the PR GitHub will automatically close the issue for you (I only learned this last week)_

That's pretty much it :)

**Comment by PlagueHO** [comment]
And once I've got the unit tests complete and passing the AppVeyor CI build will also start passing so you'll be able to tell if your branch changes break anything etc.

**Comment by DragonReach** [comment]
Ok, using Visual Studio community edition – so hope I set this up right to push the pull requests

**Comment by PlagueHO** [comment]
The GitHub extension for VS 2015 does support PR's as far as I can remember. The way I create PR's is via the GitHub web site. VIsual Studio Code is also a really great choice for editing PowerShell - much faster and simpler than VS 2015. I use VS Code myself (after using VS 2013/VS 2015 for ages).

Just browse to your branch and click the New Pull Request button and it'll usually suggest the upstream fork (my one) and show you what has changed.

I personally use the Git command line tools though for everything, but everyone has their own preference.

I'd recommend something like this:
http://gitimmersion.com/

To get a bit more familiar with the fundamentals of Git.

**Comment by PlagueHO** [comment]
Just a couple of questions:
You mentioned:

> Removed extraneous entries for setupcompleteps file

What were the extraneous entries you removed?

> Renamed $AdmininistratorCredential to $AdminCredential to correct typo and ease reading

Was this everywhere in the LabBuilder.psm1 code?

**Comment by DragonReach** [comment]
Looks like the current build has taken the ones I saw are out.

And yes I renamed it throughout – Just did a search and replace

**Comment by PlagueHO** [comment]
Oh - I just realized what you meant about the typo in the variable name - I didn't notice the extra letters when I read your comment.

**Comment by DragonReach** [comment]
Items addressed in separate issues.
