### ISSUE TITLE
#Requires RunAsAdministrator means Test for Admin will never be false

### ISSUE THREAD

**Issue by MS-MatthewWalker** [PlagueHO/LabBuilder#129]
PowerShell leveraging the #Requires statement will make sure the script fails at the start if not running as Admin -- so test for Admin is redundant

**Comment by PlagueHO** [comment]
Good point.

Although one thing I've seen other scripts do, rather than use the #Requires -RunAsAdministrator, they perform an administrator test and then restart PS in Administrator mode. Worth implementing? Or shall I just remove the IsAdmin code?

**Comment by MS-MatthewWalker** [comment]
Better to restart with Admin and remove the #Requires

**Comment by PlagueHO** [comment]
Cool. Will do!

**Comment by Sjark** [comment]
Not sure if this is possible with a module. I know it it possible with a normal .ps1 script, cause then you will just rerun the script in administrative mode, but I don't think you can do the same when using import-module.

I believe #Requires statement is the correct way to go here.

**Comment by PlagueHO** [comment]
@Sjark - You are completely right. Making the change now so I can close this one :+1: No idea why I didn't think this through.
