### ISSUE TITLE
Catch Terminating Error in Convert-WindowsImage if DISM-PowerShell-Cmdlets are below required version

### ISSUE THREAD

**Issue by m0rgenthau** [PlagueHO/LabBuilder#179]
Using unupdated dism cmdlets (or having multiple ADKs installed) causes Convert-WindowsImage to raise a terminating error. 
TemplateVHD creation should be stopped then.
[Convert-WindowsImageTranscript.txt](https://github.com/PlagueHO/LabBuilder/files/197983/Convert-WindowsImageTranscript.txt)

In this example, i was using DISM-PowerShell-Cmdlets (Version 6.3.0.0) for creation of a W2K16TP4 vhdtemplate.
Workaround: 
- Get latest ADK
- Import-Module "C:\Program Files (x86)\Windows Kits\10\Assessment and Deployment Kit\Deployment Tools\amd64\DISM" (your install path may vary ;) )

- [x] Verison of PowerShell you're using
PSVersion 5.0.10586.117
- [x] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
Console
- [x] Operating system you're running
Windows 8.1 with update
- [x] Version of LabBuilder you're using (use `Get-Module -Name LabBuilder`)
0.7.3.801

**Comment by PlagueHO** [comment]
Thanks @m0rgenthau - I'll get onto this today.
