### ISSUE TITLE
Avoid using names for VMIntegrationServices

### ISSUE THREAD

**Issue by m0rgenthau** [PlagueHO/LabBuilder#183]
Boot of VMs is checked by querying the state of VMIntegrationService Heartbeat.
For some reason the Name name attribute of VMIntegrationServices are related to the local culture, resulting in an infinite loop.
Example for my german system:

PS C:\Windows\system32> Get-VMIntegrationService -VMName Win10 -name Heartbeat
Get-VMIntegrationService : Ein Parameter ist ungültig. Es wurde keine Integrationskomponente mit dem angegebenen Namen gefunden.
In Zeile:1 Zeichen:1
+ Get-VMIntegrationService -VMName Win10 -name Heartbeat
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-VMIntegrationService], VirtualizationInvalidArgumentException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVMIntegrationServiceCommand

Correct name for german localization would be "Takt"...

PS C:\Windows\system32> Get-VMIntegrationService -VMName Win10 -name Takt

VMName Name Enabled PrimaryStatusDescription SecondaryStatusDescription
------ ---- ------- ------------------------ --------------------------
WIN10  Takt True    OK                       OK                        

Fortunately, there is also an ID:
PS C:\Windows\system32> (Get-VMIntegrationService -VMName Win10 -name Takt).ID
Microsoft:818E0E15-9BE8-4B36-92CC-3C5F44227C1B\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47

General localization problem is also discussed in the german technet:
https://social.technet.microsoft.com/Forums/de-DE/154917de-f3ca-4b1e-b3f8-23dd4b4f0f06/getvmintegrationservice-sprachabhngig?forum=powershell_de

Solution could be, to get the correct name by ID:
PS C:\Windows\system32> $HeartBeatNameCultureNeutral = Get-VMIntegrationService -VmName $VM.Name | Where-Object{$_.ID -eq "Microsoft:818E0E15-9BE8-4B36-92CC-3C5F44227C1B\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47"}

PS C:\Windows\system32> $HeartBeatNameCultureNeutral.Name
Takt

This is only for querying the state of the IntegrationService. For **changing** its state, you must use the "english" names...

PS C:\Windows\system32> Disable-VMIntegrationService -VMName Win10 -name Takt
Disable-VMIntegrationService : Ein Parameter ist ungültig. Der für den Integrationsdienst angegebene Name ist ungültig. Verwenden Sie Platzhalterzeichen, oder geben Sie einen der gültigen Namen für den Integrationsdienst an: "Time Synchronization", 
"Heartbeat', "Key-Value Pair Exchange", "Shutdown", "VSS" oder "Guest Service Interface".
In Zeile:1 Zeichen:1
+ Disable-VMIntegrationService -VMName Win10 -name Takt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Disable-VMIntegrationService], VirtualizationInvalidArgumentException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.DisableVMIntegrationServiceCommand

Will try to fix this and give you a PR (yay, first PR for me ;) )

- [ ] Verison of PowerShell you're using
PSVersion 5.0.10586.117
- [ ] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
Console
- [ ] Operating system you're running
Windows 8.1 with update
- [ ] Version of LabBuilder you're using (use `Get-Module -Name LabBuilder`)
0.7.3.801

**Comment by m0rgenthau** [comment]
Format of IntegrationService IDs is $VM.ID \ ID_Integrationservice.

Example for Heartbeat:

`$VMs = Get-VM

foreach($vm in $vms)
{
    
    $IntegrationServices = Get-VMIntegrationService -VMName $vm.name | Where-Object{$_.ID -like "*\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47"}

    Foreach ($service in $IntegrationServices)
    {
        Write-Host "VM: $($vm.ID) ID: $($service.Id)"
    }

}`

VM: d7ee215a-ea06-4b90-ba8b-d85375198c9f ID: Microsoft:D7EE215A-EA06-4B90-BA8B-D85375198C9F\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47
VM: a2ae3371-8b7d-45f4-afd9-c3d612c161b9 ID: Microsoft:A2AE3371-8B7D-45F4-AFD9-C3D612C161B9\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47
VM: 962b3912-fbdd-412f-96cd-67a24e9b2f4b ID: Microsoft:962B3912-FBDD-412F-96CD-67A24E9B2F4B\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47
VM: 3cfc2a19-399d-40a7-87f4-6d82de892165 ID: Microsoft:3CFC2A19-399D-40A7-87F4-6D82DE892165\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47
VM: 7ecbdd1a-1ef9-4d21-abdc-77bf5427dac0 ID: Microsoft:7ECBDD1A-1EF9-4D21-ABDC-77BF5427DAC0\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47
VM: 5f5a7f9e-816e-4354-868b-0a20f503d0e9 ID: Microsoft:5F5A7F9E-816E-4354-868B-0A20F503D0E9\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47
VM: 818e0e15-9be8-4b36-92cc-3c5f44227c1b ID: Microsoft:818E0E15-9BE8-4B36-92CC-3C5F44227C1B\84EAAE65-2F2E-45F5-9BB5-0E857DC8EB47

**Comment by PlagueHO** [comment]
@m0rgenthau - excellent work there! Well done picking that up :+1: I should definitely be thinking about localization more. I'll review your PR ASAP. Thanks again for submitting it! :smile:

**Comment by PlagueHO** [comment]
Note: if you add: ```Fixes #182``` (or whatever the issue number is) to the end of the PR title, Github will helpfully close the issue automatically once the PR is merged :+1: 
Fixed by PR #184

**Comment by Coder-666** [comment]
Interesting, this also affects xHyper-V DSC resource
