### ISSUE TITLE
Create Multiple VMs from one definition

### ISSUE THREAD

**Issue by MS-MatthewWalker** [PlagueHO/LabBuilder#185]
Potential enhancement - Add a variable in VM definition to allow creation of multiple VMs with the same config and increment the name by 1 each time, so names become something like VM1, VM2, VM3 etc... 

Rather than having to create multiple entries in the XML for each one.

If static IP would also want to increment by 1 each time as well.

**Comment by PlagueHO** [comment]
Good point about the IP addresses (I didn't think about that) :+1:

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - trying to come up with an intuitive name for the attribute to cause multiple VM's to be generated for a single entry.

At the moment I'm using:
**Duplicate**

I thought **Replicate** - seems wrong as it implies something to do with VM replication (at least to me). **Multiply** seems wrong too.

Your thoughts?

**Comment by ericreiss** [comment]
Can I make a suggestion.  You mentioned generate, so why not "Generate".  A synonym would be "Spawn" for another suggestion.

**Comment by MS-MatthewWalker** [comment]
instances could work as well

**Comment by PlagueHO** [comment]
@ericreiss - I like generate, although ideally it should indicate a number. For my programmer mind @MS-MatthewWalker 's "instances" actually makes a lot of sense. Perhaps `InstanceCount`?

**Comment by MS-MatthewWalker** [comment]
`InstanceCount` seems best to me.
