### ISSUE TITLE
Creating External Switches - define XML attrib for binding adapter

### ISSUE THREAD

**Issue by m0rgenthau** [PlagueHO/LabBuilder#189]
When creating an external switch, the first non-virtual adapter will be bound.

```
$null = New-VMSwitch `
                        -Name $SwitchName `
                        -NetAdapterName (`
                            Get-NetAdapter | `
                            Where-Object { $_.Status -eq 'Up' -and $_.InterfaceDescription -notlike "Hyper-V Virtual*" } | `
                            Select-Object -First 1 -ExpandProperty Name `
                            )
```

The Where-Object statement should be something like:
Where-Object { $_.Status -eq 'Up' -and $_.InterfaceDescription -notlike **"Hyper-V*"** }
Again, localization, my german adapters are named "Hyper-V-Adapter [...]" - but i guess with "Hyper-V*" you should get localizations.

But still not nice, if you have multiple active network adapters.
An XML Attrib like 

```
<switch name="External" type="External">
<vmswitchbindingadapter description="XXXXX" mac="0000000000" />
</switch>
```
would be nice.

**Comment by PlagueHO** [comment]
@m0rgenthau  - another good point!

Might I suggest using XML like this (only because it requires a little less code to implement) :
```xml
<switch name="External" type="External" bindingadapterdescription="XXXX" bindingadaptermac="0000000000" />
```

Or alternately we could do a better job of detecting Hyper-V adapters by ignoring any adapters using the VMSwitch.sys driver:
```powershell
Where-Object { $_.Status -eq 'Up' -and $_.DriverName -notlike '*\vmswitch.sys' }
```

**Comment by PlagueHO** [comment]
Actually, on second thoughts, I think the BindingAdapterDescription is the best way because it allows you to select the Adapter you actually want to use.

**Comment by PlagueHO** [comment]
Sorry, more thoughts on this. Rather than using the Adapter description it would just be better to use the Name:
```xml
<switch name="External" type="External" bindingadapter="XXXX" bindingadaptermac="0000000000" />
```

If a BindingAdapter is not found or the attribute is not set then we failback to using this code to determine the adapter:
```powershell
                    $null = New-VMSwitch `
                        -Name $SwitchName `
                        -NetAdapterName (`
                            Get-NetAdapter | `
                            Where-Object { $_.Status -eq 'Up' -and $_.DriverName -notlike '*\vmswitch.sys' } | `
                            Select-Object -First 1 -ExpandProperty Name `
                            )
```

Would this solve the issue?

**Comment by m0rgenthau** [comment]
Fine with me!

**Comment by PlagueHO** [comment]
Working on this now - and I just realized there is a .Virtual property of the Network Adapter - no need for detecting drivers or anything like that at all!
