### ISSUE TITLE
Issue checking if BindingAdapter is already bound to a switch

### ISSUE THREAD

**Issue by m0rgenthau** [PlagueHO/LabBuilder#196]
If you already have multiple External VM Switches installed, the check fails, cause:
 Get-VMSwitch | ?{$_.SwitchType -eq 'External'} will give you a System.Object.
Get-VMNetWorkAdapter -Name only accepts Strings.

Solution:
# Check this adapter is not already bound to a switch
                    $VMSwitchNames = (Get-VMSwitch | Where-Object{$_.SwitchType -eq 'External'}).Name
					ForEach ($VmSwitchName in $VmSwitchNames)
					{
						$MacAddress += `
							(Get-VMNetworkAdapter `
                            -ManagementOS `
                            -Name $VmSwitchName -ErrorAction SilentlyContinue).MacAddress
						
					}

**Comment by PlagueHO** [comment]
Ah I see! Excellent work. Thank you :+1:

**Comment by PlagueHO** [comment]
I've manually merged this one!
