### ISSUE TITLE
Add CR to SetupComplete cmd file

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#20]
@DragonReach:
Added Carriage returns and a timeout to deal with some sort of timing issue that was preventing initial setup to not return and PS1 to not run.

```powershell
    # Write out the CMD Setup Complete File
    $SetupCompleteCmd = @"
@echo SetupComplete.cmd Script Started... >> %SYSTEMROOT%\Setup\Scripts\SetupComplete.log `r
Timeout 30 `r
powerShell.exe -ExecutionPolicy Unrestricted -Command `"%SYSTEMROOT%\Setup\Scripts\SetupComplete.ps1`" `r
@echo SetupComplete.cmd Script Finished... >> %SYSTEMROOT%\Setup\Scripts\SetupComplete.log `r
@echo Initial Setup Completed - this file indicates that setup has completed. >> %SYSTEMROOT%\Setup\Scripts\InitialSetupCompleted.txt`r
"@
    $null = Set-Content `
        -Path (Join-Path -Path $VMLabBuilderFiles -ChildPath 'SetupComplete.cmd') `
        -Value $SetupCompleteCmd -Force -Encoding Ascii
```

**Comment by PlagueHO** [comment]
@DragonReach: Are you sure about this one? I checked the file that is being produced and it does look like it has CRLF's at the end of each line:

![2016-02-11_15-02-11](https://cloud.githubusercontent.com/assets/7589164/12967949/871489f2-d0d0-11e5-8be6-140a9120f437.png)

Also, the:
```powershell
= @"
"@
```
is supposed to put CRLF at the end of each line (great for creating HTML snippets, XML etc).

I suspect the delay is actually creating the certificate (sometimes it does take 20-30 seconds - no idea why).

**Comment by DragonReach** [comment]
Weird all the ones I looked at didn’t have CR LF until I added the `r

I checked it several times.

**Comment by PlagueHO** [comment]
@DragonReach:
Was this in the VM or the "LabBuilder Files" folder on the Host for the VM? Although I can't see why they would be different.

Did you notice if the SetupComplete.ps1 file had missing CRLF as well or just SetupComplete.cmd?

**Comment by DragonReach** [comment]
Both places

Was just in the CMD, the PS1 looked fine, which is part of what confused me.

**Comment by PlagueHO** [comment]
That is really odd.

Was it missing from every line?

There is code in there to allow adding custom setup complete actions- I wonder if this has something to do with it. The custom setup code is inserted exactly where the Timeout command goes...

**Comment by DragonReach** [comment]
Not really sure, but I left systems sit for hours a few times just to make sure it wasn’t waiting on something.

**Comment by PlagueHO** [comment]
So I'm correct in assuming that it hadn't produced the file:
%SYSTEMROOT%\Setup\Scripts\SetupComplete.log

**Comment by DragonReach** [comment]
It created it, but only put in the started lines --- and that reminds of what the extraneous messaging was – setupcompleteps adds the start and stuff twice between the two sections that create it.

**Comment by PlagueHO** [comment]
The SetupStarted messages appear twice because there is one for the CMD file and one for the PS1 file. I added the second one because early on I had some issues with starting the PS1 script.
