### ISSUE TITLE
Initializing a Lab-VM: ExposeVirtualizationExtensions can be $null

### ISSUE THREAD

**Issue by m0rgenthau** [PlagueHO/LabBuilder#201]
When initializing a LabVM, the VM Attribute "ExposeVirtualizationExtensions" can be $NULL - if the vmtype doesn't support this feature. 

Example:
```
PS C:\Windows\system32> Get-VM -name "Playground SA-DC1" | fl


Name             : PLAYGROUND SA-DC1
State            : Off
CpuUsage         : 0
MemoryAssigned   : 0
MemoryDemand     : 0
MemoryStatus     :
Uptime           : 00:00:00
Status           : Normaler Betrieb
ReplicationState : Disabled
Generation       : 2



PS C:\Windows\system32> $a = (get-vmprocessor -vmname "PLAYGROUND SA-DC1").ExposeVirtualizationExtension
PS C:\Windows\system32> $a -eq $null
True
PS C:\Windows\system32>
```

Fixed this by adding the check on -ne $null
```
        if ( ($VM.ExposeVirtualizationExtensions -ne (Get-VMProcessor -VMName $VM.Name).ExposeVirtualizationExtensions) -and `
			 ((Get-VMProcessor -VMName $VM.Name).ExposeVirtualizationExtensions -ne $null) )
```

Will synch it to pull request #198

**Comment by m0rgenthau** [comment]
Fixed in https://github.com/PlagueHO/LabBuilder/pull/198/commits/728745b6dabbf88016917e38a9e10cf7d65b6f3e

sry for the github usage fail -.-

**Comment by PlagueHO** [comment]
@m0rgenthau - Lol - oh right - and you were the one who fixed it too :) I just need you to fix the merge conflict and I'll merge this.

I'll close this :+1:
