### ISSUE TITLE
Fix support for NAT Virtual Switches

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#228]
The initial method of creating NAT virtual switches was to use a Virtual Switch type of NAT. This is no longer supported.

The correct method is to create an Internal Switch and then call the New-NetNat cmdlet:
https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/setup_nat_network

**Comment by MS-MatthewWalker** [comment]
Keep in mind this is meant for use with containers as well.

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - true true. One day it might be nice to add the ability to spin up container images as part of a Lab - but that won't be for a while yet. This is mainly to fix the problem where if a NAT switch is currently specified an error is thrown.

**Comment by PlagueHO** [comment]
Some more info:

https://blogs.technet.microsoft.com/virtualization/2016/05/05/windows-container-networking/
