### ISSUE TITLE
Add a Minimum Windows build parameter to Lab config

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#233]
Some labs require specific host builds to run correctly. For example labs that contain NAT switches require build 14295. So add a minimum build attribute to the Lab that will prevent it from building a lab if the host isn't at least this version.

**Comment by MS-MatthewWalker** [comment]
Perfect timing, as I just found out Virtualization extensions will not work with the Win10 Nov release when the VM is TP5

**Comment by PlagueHO** [comment]
Cool! I'll implement this today.
