### ISSUE TITLE
ExposeVirtualizationExtensions fails on builds of Windows 10 above 14352

### ISSUE THREAD

**Issue by MS-MatthewWalker** [PlagueHO/LabBuilder#251]
If you add the option to expose virtualization extensions for a VM being created on a host that is build 14352 or later you will get an error similar to the following 

```
Set-VMProcessor : Failed to modify device 'Processor'.
Cannot modify property.
'HVFC DC' failed to modify device 'Processor'. (Virtual machine ID 44161EC3-AA72-4CB0-8E06-FB23E
Cannot modify property without enabling VirtualizationBasedSecurityOptOut.
At D:\Scripts\lib\public\vm.ps1:1132 char:17
+                 Set-VMProcessor `
+                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-VMProcessor], VirtualizationException
    + FullyQualifiedErrorId : NotSupported,Microsoft.HyperV.PowerShell.Commands.SetVMProcessor

```
In order to resolve you need to include the following command prior to exposing virtualization extensions

` Set-VMSecurity -VMName $VMname -VirtualizationBasedSecurityOptOut $true `

**Comment by PlagueHO** [comment]
@MS-MatthewWalker - good catch! I've only just installed this version of Win 10. Awesome info on the fix too. I'll get a change through for that now.

Cheers!
