### ISSUE TITLE
Can't create generation 1 VM 

### ISSUE THREAD

**Issue by MS-MatthewWalker** [PlagueHO/LabBuilder#255]
Section for creating a VM only creates Generation 2 VMs, the VHD creation will create both UEFI boot and BIOS boot images, but the VM creation is hard set to only create Generation 2. 

Tried to add the Functionality to the VMTemplate and VM modules, but generates error as below 

```
The property 'Generation' cannot be found on this object. Verify that the property exists and can be set.
At D:\Scripts\lib\public\vmtemplate.ps1:266 char:13
+             $VMTemplate.Generation = $Template.generation
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```

Code added to VMTemplate.ps1

```
        if ($Template.generation)
        {
            $VMTemplate.generation = $Template.generation
        }
        elseif (-not $Template.generation)
        {
            $VMTemplate.generation = 2
        } # if
```

not finding an object definition that would prevent this from working.

**Comment by PlagueHO** [comment]
Thanks @MS-MatthewWalker - I'll take a look at this tomorrow night. Good catch- I often find myself forgetting about Gen1 VM's.

**Comment by MS-MatthewWalker** [comment]
So I'm an idiot and didn't see the class definitions in the LabBuilder.PSM1 file I can easily modify those to accomodate the required pieces and the code for VM creation -- Once done I will submit a pull request.  Also fixed a bunch of little typos (all comments, no read code changes)

**Comment by PlagueHO** [comment]
Doh! Oh right! :smile: No worries - submit away! Cheers sir!

**Comment by MS-MatthewWalker** [comment]
So I had to do a bit more work than planned - Device naming only works with Generation 2 VMs, and must be version 6.2 or higher.  Also found an issue with creating shared VHDs - only need to set support PR and the VHD must reside on a CSV.
