### ISSUE TITLE
Indicate a working Module version

### ISSUE THREAD

**Issue by Zattom** [PlagueHO/LabBuilder#259]
It happens that some Labs, for eg: "Sample_WS2012R2_DomainSQL2014.xml", won't work until the end because some DSC resources are updated in the meantime and aren't working with the Lab anymore (regression inner some functions or variables).
In my case, xDisk will fail to attribute letter when creating a new partition on the SQL, then SQL sources will not be copied on this partition, then SQL will not be installed, etc.

Is it possible to implement `Import-Module -Name xxx -RequiredVersion y.y.y.y`, leaving that the command is commented for our information. We would be aware that this version number working during your release.

This could save time troubleshooting those kind of issues.

Kinds regards,
Pierrick L.

**Comment by MS-MatthewWalker** [comment]
Can you provide a copy of a non-functioning config?  I have not run into this issue.

**Comment by PlagueHO** [comment]
Hi @Zattom  - so is the xDisk resource module failing? If so I'd want to log that with the PowerShell DSC team to get it sorted. There is a program at the moment to rework some of these resources so if there is a problem with them then it would be great to get them sorted.

You could of course create a new copy of the DSC Library config with the RequiredVersion set. You'd need to change the LabConfig.xml file to use your new specific DSC Library config.

Is it possible to get log output of the DSC config for the problem node?

**Comment by Zattom** [comment]
Thank you for your interest !

I've apply an unit test on the xDisk ressource with the SQ2014 lab which is using MEMBER_SQLSERVER2014_DSC.ps1. I discovered that this config call  `xDisk DVolume` **1** hard coded. 

I've done a Get-Disk on my VM and the result is that Volume 1 is C:
Disk 0 is the blank .vhdx attached used to store the SQL 2014 sources... Changing this value to "0" has made it operational.

I forgot to check the _DSC.ps1_ script but I don't know how Windows handle the volume number !
