### ISSUE TITLE
Add function to create template disks from ISO image

### ISSUE THREAD

**Issue by DragonReach** [PlagueHO/LabBuilder#27]
`  <TemplateDisks>
    <Prefix>Win2016-</Prefix>
    <TemplateDisk Name='StandardFullG2.VHDX'
                  IsNano='N'
                  WimImage='SERVERSTANDARD'
                  Generation='2'
                  VHDFormat='VHDX'
                  PartitionStyle='GPT'
                  />
    <TemplateDisk Name='DataCenterCoreG2.VHDX'
              IsNano='N'
              WimImage='SERVERDATACENTERCORE'
              Generation='2'
              VHDFormat='VHDX'
              PartitionStyle='GPT'
                  />
    <TemplateDisk Name='DataCenterNanoG2.VHDX'
              IsNano='Y'
              WimImage='CORESYSTEMSERVER_INSTALL'
              Generation='2'
              VHDFormat='VHDX'
              PartitionStyle='GPT'
              Packages='FailoverCluster,Guest,Storage,Defender'
                  />
  </TemplateDisks>`

XML syntax  - Once I have the function written I will add and submit pull request

**Comment by PlagueHO** [comment]
Cool - this has been on my todo list since I first started this project :smile: 

Suggestion:

I am presuming the Prefix is used to append "Win2016-" onto the beginning of the VHDx filename?
If so, then perhaps make the <prefix> a property of the <TemplateDisk> for each template.

Also, how will the path to the Source ISO that will build these templates be provided?
 
Have you made a fork of this repo? You'll want to do that first so you can make changes to your fork and the submit the PR from that fork (or a branch of your fork most likely). Also, submit PR's to the Dev branch of this repo rather than master.

**Comment by DragonReach** [comment]
Ok, that makes sense for the prefix – I already have all the code to do this, just modifying to fit the format.  Some of which is borrowed from your nanoserver creation script ☺

On mine I added the source iso into settings
I’ll do that as soon as I figure out how to fork it

Like I said I’m still learning ☺

**Comment by PlagueHO** [comment]
Oh I just realized I already have an attribute in the <template> for controlling the ISO to use to create the template disk. It is:
installiso=".\Tests\PesterTestConfig\10240.16384.150709-1700.TH1_CLIENTENTERPRISE_VOL_X64FRE_EN-US.iso"

**Comment by DragonReach** [comment]
Ok, apparently I screwed - pull request went to your dev branch and i was just trying to update my fork.

**Comment by PlagueHO** [comment]
So PR #35 was not meant to be a PR, but a commit to your own fork? If so, just cancel/close the PR. :smile:

**Comment by PlagueHO** [comment]
FYI, I've nearly completed Issue #9 (Support for multiple VHDs). You can see it in [this branch](https://github.com/PlagueHO/LabBuilder/tree/Issue-9-Support-Multiple-Data-Disks).

Once it is complete (later on today) I'll merge this change down into my Dev branch. What you'll then want to do is fetch my dev branch and merge it down into your dev branch.

The commands to do this are (in case you're interested):
```
cd <LabBuilder folder on your local machine>
; pull the upstream dev branch (my dev branch) down into your local git repository
git fetch upstream dev
; make sure your dev branch is the currently checked out branch
git checkout dev
; merge changes from my my dev branch into your dev branch
git merge upstream dev
```
Your local dev branch will then have your changes as well as the new changes I've made.

**Comment by DragonReach** [comment]
Thanks

**Comment by PlagueHO** [comment]
I'll close this issue now because it has been merged.
