### ISSUE TITLE
Setup aborts with error message "The member 'SubnetMask' is not valid

### ISSUE THREAD

**Issue by tplive** [PlagueHO/LabBuilder#280]
Ran into this issue, and I see on Gitter that it's been recognized, but no issue has been filed here, so I thought I'd contribute.. :)

- [5.1.14393.0 ] Verison of PowerShell you're using
- [Console Host ] PowerShell host you're using (eg. Console Host, ISE, Visual Studio)
- [ Windows 10] Operating system you're running
- [0.8.3.1087 ] Version of LabBuilder you're using (use `Get-Module -Name LabBuilder`)

Unable to complete lab setup using template Sample_WS2016_NanoDomain.xml. Setup aborts with error message:

 ```
CreateDSCMOFFiles : At C:\MyLab\vm\TQNANOTEST.COM\TQNANOTEST.COMSA-DC1\LabBuilder  Files\DSCNetworking.ps1:7 char:9
 +         SubnetMask     = '0'
 +         ~~~~~~~~~~
 The member 'SubnetMask' is not valid. Valid members are
 'AddressFamily', 'DependsOn', 'InterfaceAlias', 'IPAddress', 'PrefixLength', 'PsDscRunAsCredential'. 
 At C:\MyLab\vm\TQNANOTEST.COM\TQNANOTEST.COMSA-DC1\LabBuilder  Files\DSCNetworking.ps1:23 char:9
 +         SubnetMask     = '0' 
 +         ~~~~~~~~~~
```

I see on Gitter that the issue has been identified by @SombreSire_twitter on 5/11/2016 @12:04:

ok, I solved it, I had to modify a few files (labbuilderconfig-schema.xsd, dsc.ps1, and the samples files)
I found that SubnetMask is used in the module xNetworking version 2.12.0.0 but has been replaced by PrefixLength in the version 3.0.0.0

I installed the LabBuilder module today, and also cloned the main branch, and still found SubnetMask being used. So my guess is the fix hasn't been incorporated yet? :)

Best regards,
@tplive

**Comment by PlagueHO** [comment]
@tplive - oh great catch! Thank you!

I should have predicted this problem as I was the one who made the change in xNetworking to change the SubnetMask to PrefixLength in xIPAddress :grin:

I'll fix this over this weekend. Thanks again for pointing this out!

**Comment by PlagueHO** [comment]
@tplive - I've fixed this now. The LabBuilder module will now also ensure xNetworking 3.0.0.0 or above is installed on the host and install it from PSGallery if it missing or an older version is installed.

I've released this version to Master which will have deployed this to PSGallery.

Thanks again for reporting this!

**Comment by PlagueHO** [comment]
I can confirm the CI/CD process has deployed this as [version 0.8.3.1108](https://www.powershellgallery.com/packages/LabBuilder/0.8.3.1087).
