### ISSUE TITLE
Using NPAS-Policy-Server on Server 2016 VMs fails

### ISSUE THREAD

**Issue by BristleBeard** [PlagueHO/LabBuilder#283]
Using the console on Server 2016 Hyper-core, any resources using NPAS fails when creating a 2016 NPAS/DHCP server, as it seems you must install 'NPAS' rather than using 'NPAS-Policy-Server'.

This was using 0.8.3.1116.

**Comment by PlagueHO** [comment]
Hi @BristleBeard - thanks for raising this issue. I see what you mean.

What I've done is added a new DSC Library for DHCP + NPAS on Windows Server 2016. I would have just updated the normal one to just install NPAS, but this would end up installing HCAP and Health Registration Authority (which both I think are deprecated in Windows Server 2016).

Is this OK?

**Comment by PlagueHO** [comment]
This has been released to the PS Gallery in version 0.8.3.1124

**Comment by BristleBeard** [comment]
That works perfectly fine for my testing. I'll give it a spin and report back.

**Comment by BristleBeard** [comment]
I an confirm this is now working, though it uncovered another issue on authorizing the DHCP server in AD, as detailed in #286
