### ISSUE TITLE
Add VM Computer name to credentials used to connect to VM

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#3]
Have to had new VM into trusted host. - added code - In addition set credentials to include OS Name in Function Wait-LabVMInit

Actual fix

```powershell
$Username = $VM.ComputerName + '\Administrator'
    Write-Verbose $Username
    [PSCredential] $AdmininistratorCredential = New-Credential `
        -Username $Username `
        -Password $VM.AdministratorPassword
```

**Comment by PlagueHO** [comment]
@DragonReach
I'm just merging this into the master branch.

**Comment by PlagueHO** [comment]
I'm going to reopen this issue because the solution of adding the computer name to the credentials only works for machines that aren't AD domain controllers. DC's can only be connected to using domain credentials.

What I might do is configure the connection to try and connect using credentials without a computername, and if it fails with an access denied then try with the computername. The connection could alternate between these two credentials.

**Comment by DragonReach** [comment]
Makes sense, I didn’t think of the domain affect until later and haven’t had a chance to get back to it.

**Comment by PlagueHO** [comment]
@DragonReach:

Actually, would it be possible to use "." instead? E.g.
.\Administrator

Would that work for both scenarios? It works for DCs

**Comment by DragonReach** [comment]
Quick test shows it works for me.

**Comment by DragonReach** [comment]
So to elaborate – I went through and replaced all my adds that appended Computername\Administrator with ‘.\Administrator’ – worked fine.

**Comment by PlagueHO** [comment]
Great! I'll implement that then.

**Comment by DragonReach** [comment]
Hey is there a non-public way to exchange emails to allow conversations to continue without polluting the actual issues?

From: Matthew Walker
Sent: Tuesday, February 9, 2016 6:32 PM
To: 'PlagueHO/LabBuilder' <reply@reply.github.com>; PlagueHO/LabBuilder <LabBuilder@noreply.github.com>
Subject: RE: [LabBuilder] Add VM Computer name to credentials used to connect to VM (#3)

So to elaborate – I went through and replaced all my adds that appended Computername\Administrator with ‘.\Administrator’ – worked fine.
