### ISSUE TITLE
Addition of management IP address to TrustedHosts fails when TrustedHosts is empty

### ISSUE THREAD

**Issue by stuart475898** [PlagueHO/LabBuilder#314]
**PowerShell Version**:
```
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316
```

**Host**: Console + Visual Studio Code

**OS**: Windows 10 Pro 1809

```
PS C:\> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

**LabBuilder Version**:
```
PS C:\> Get-Module -Name LabBuilder

ModuleType Version    Name 
---------- -------    ----           
Script     1.0.1.40   LabBuilder
```

**Issue:**
When trying to build out the sample lab _Sample_WS2016_NanoDomain_ as per https://dscottraynsford.wordpress.com/2016/10/04/easily-create-a-hyper-v-windows-server-2016-ad-nano-server-lab/, once the first VM starts, LabBuilder tries to establish its PSSession and it becomes stuck in a loop stating: 

`VERBOSE: [21:37:38]: Connection to VM 'NANOTEST.COM SA-DC1' failed (Cannot convert 'System.Object[]' to the type 'System.String' required by the parameter. Specified method is not supported.), retrying in 5 seconds`

Digging into this, I find that the exception is being thrown when trying to add the VM's management IP address to _TrustedHosts_ on lines 5799 - 5802 of LabBuilder.psm1:

```
Set-Item `
       -Path WSMAN::localhost\Client\TrustedHosts `
       -Value $trustedHosts `
       -Force
```

This only appears to be a problem if _TrustedHosts_ is blank. 

**To Reproduce:**

```
PS C:\> $managementAdapter = Get-VMNetworkAdapter -VMName "NANOTEST.COM SA-DC1" | Where-Object -Property SwitchName -EQ -Value "NANOTEST.COM Lab Management"
PS C:\> $managementAdapterIpAddresses = $managementAdapter.IPAddresses
PS C:\> $managementAdapterIpAddress = $managementAdapterIpAddresses | Where-Object -FilterScript { $_.Contains('.') }
PS C:\> $managementAdapterIpAddress
169.254.218.179
PS C:\> $managementAdapterIpAddress.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object


PS C:\> (Get-Item -Path WSMAN::localhost\Client\TrustedHosts).Value

PS C:\> Set-Item -Path WSMAN::localhost\Client\TrustedHosts -Value $managementAdapterIpAddress
Set-Item : Cannot convert 'System.Object[]' to the type 'System.String' required by the parameter. Specified method is
not supported.
At line:1 char:1
+ Set-Item -Path WSMAN::localhost\Client\TrustedHosts -Value $managemen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Item], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetItemCommand

PS C:\>
```

This does not occur if the _$managementAdapterIpAddress_ is a string:

```
PS C:\> Set-Item -Path WSMAN::localhost\Client\TrustedHosts -Value "$managementAdapterIpAddress"
PS C:\> (Get-Item -Path WSMAN::localhost\Client\TrustedHosts).Value
169.254.218.179
```

**Fix:**
I resolved this by enclosing the $ipAddress variable in quotes on line 5793 of LabBuilder.psm1:

`$trustedHosts = "$ipAddress"`

If there are already values in _TrustedHosts_, then no exception is thrown as line 5797 converts it all to a string anyway:

`$trustedHosts = "$trustedHosts,$ipAddress"`

**Comment by PlagueHO** [comment]
Great catch @stuart475898 - thanks for posting the solution. I'll get this fixed today!

**Comment by PlagueHO** [comment]
The new version will be released to the PSGallery shortly.
