### ISSUE TITLE
Infinite loop when running Stop-Lab with missing VMs

### ISSUE THREAD

**Issue by stuart475898** [PlagueHO/LabBuilder#316]
**PowerShell Version**:
```
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316
```

**Host**: Console + Visual Studio Code

**OS**: Windows 10 Pro 1809

```
PS C:\> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

**LabBuilder Version**:
```
PS C:\> Get-Module -Name LabBuilder

ModuleType Version    Name 
---------- -------    ----           
Script     1.0.1.40   LabBuilder
```

**Issue:**

In the event any VMs are missing when running Stop-Lab, an infinite loop presents the following messages:

```
New-LabException : The VM 'NANOTEST.COM SA-NANO1' does not exist.
At C:\Program Files\WindowsPowerShell\Modules\LabBuilder\1.0.1.40\LabBuilder.psm1:10374 char:21
+                     New-LabException @exceptionParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-LabException], Exception
    + FullyQualifiedErrorId : VMDoesNotExistError,New-LabException

Get-VM : Hyper-V was unable to find a virtual machine with name "NANOTEST.COM SA-NANO1".
At C:\Program Files\WindowsPowerShell\Modules\LabBuilder\1.0.1.40\LabBuilder.psm1:10389 char:22
+                 if ((Get-VM -VMName $VMName).State -ne 'Off')
+                      ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (NANOTEST.COM SA-NANO1:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
```
This appears to be due to the _while_ loop running on lines 10354 to 10415. If the VM is not found on lines 10361 to 10363, the if statement on lines 10364 to 10375 fails and an exception is thrown.

The infinite loops appears to occur because the if statement on lines 10389 to 10393 will _always_ evaluate _$true_ for the missing VMs, and we will never break out of the loop from the _if_ statement on lines 10399 to 10407.

**Fix:**
My initial thoughts are that modifying the conditions on line 10389 would mitigate this, which I have tested satisfactorily:

```
if ($VMObject -and (Get-VM -VMName $VMName).State -ne 'Off')
```

This prevents the loop and removes the _Get-VM_ exception thrown.

An exception is still thrown from lines 10367 to 10371 due to the missing VM - my thoughts are a missing VM is of little significance to the _Stop-Lab_ command, so this exception could be changed to a _LabMessage_ stating the VM is missing, resulting in no exceptions being thrown.

**Comment by PlagueHO** [comment]
Thanks for raising this @stuart475898 - just testing the fix now. Will release shortly.
