### ISSUE TITLE
dsclibrary/STANDALONE_ROOTCA.DSC.ps1 CAConfig Should be empty

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#320]
This value is not required when Web Enrollment Server is on the same server as the CA.

**Comment by kungfu71186** [comment]
This also exists in https://github.com/PlagueHO/LabBuilder/blob/291e6461a19d2beec02a1b7ed16e8e8da45c869d/src/dsclibrary/MEMBER_SUBCA.DSC.ps1#L208

And possibly the other CA deployments

**Comment by PlagueHO** [comment]
Getting on to these tomorrow @kungfu71186
