### ISSUE TITLE
dsclibrary/STANDALONE_ROOTCA.DSC.ps1 waiting for wrong resource

### ISSUE THREAD

**Issue by kungfu71186** [PlagueHO/LabBuilder#321]
https://github.com/PlagueHO/LabBuilder/blob/291e6461a19d2beec02a1b7ed16e8e8da45c869d/src/dsclibrary/STANDALONE_ROOTCA.DSC.ps1#L263

Should be waiting for `RegisterSubCA`

**Comment by PlagueHO** [comment]
Thanks @kungfu71186 - I'll do a big batch of fixes on Thursday night (snowed under the next two nights).
