### ISSUE TITLE
dsclibrary/STANDALONE_ROOTCA.DSC.ps1 some of the CApolicy.inf parameters are not correct

### ISSUE THREAD

**Issue by kungfu71186** [PlagueHO/LabBuilder#322]
https://github.com/PlagueHO/LabBuilder/blob/291e6461a19d2beec02a1b7ed16e8e8da45c869d/src/dsclibrary/STANDALONE_ROOTCA.DSC.ps1#L63

This
`DiscreteSignatureAlgorithm` should really be `AlternateSignatureAlgorithm` and it should probably be set to 0 or not specified.

This is something I have, which is based off of this https://www.bussink.ch/?page_id=652 and this https://timothygruber.com/pki/deploy-a-pki-on-windows-server-2016-part-3/

```
[Version]
Signature="$Windows NT$"

[Certsrv_Server]
RenewalKeyLength=4096
RenewalValidityPeriod=Years
RenewalValidityPeriodUnits=20
AlternateSignatureAlgorithm=0
CNGHashAlgorithm=SHA256
CRLPeriod=Years
CRLPeriodUnits=20
CRLDeltaPeriod=Days
CRLDeltaPeriodUnits=0
LoadDefaultTemplates=0
```

**Comment by PlagueHO** [comment]
Thanks @kungfu71186 - I'll do a big batch of fixes on Thursday night (snowed under the next two nights).
