### ISSUE TITLE
dsclibrary/MEMBER_SUBCA.DSC.ps1 some of the CApolicy.inf parameters may not work

### ISSUE THREAD

**Issue by kungfu71186** [PlagueHO/LabBuilder#324]
https://github.com/PlagueHO/LabBuilder/blob/291e6461a19d2beec02a1b7ed16e8e8da45c869d/src/dsclibrary/MEMBER_SUBCA.DSC.ps1#L115

`AlternateSignatureAlgorithm` should probably be 0. This can cause some issues with non windows machines. I had some issues just getting it to trust the cert on windows itself. This was on server 2016 as well.

Again, a decent config might be something like

```
[Version]
Signature="$Windows NT$"

[Certsrv_Server]
RenewalKeyLength=4096
RenewalValidityPeriod=Years
RenewalValidityPeriodUnits=10
AlternateSignatureAlgorithm=0
CNGHashAlgorithm=SHA256
LoadDefaultTemplates=0

```

this is based on the same articles in #322

**Comment by PlagueHO** [comment]
Thanks @kungfu71186 - I'll do a big batch of fixes on Thursday night (snowed under the next two nights).
