### ISSUE TITLE
Both MEMBER_SUBCA.DSC.ps1 and STANDALONE_ROOTCA.DSC.ps1 certutil.log file not found

### ISSUE THREAD

**Issue by kungfu71186** [PlagueHO/LabBuilder#325]
https://github.com/PlagueHO/LabBuilder/blob/291e6461a19d2beec02a1b7ed16e8e8da45c869d/src/dsclibrary/STANDALONE_ROOTCA.DSC.ps1#L131

That file is not created and when trying to add content to the file, it errors out because it can't be found. I had to add a check in there and create it.

Maybe use file resource to make sure it exists or something like:
```
                $certLogFile = 'c:\windows\setup\scripts\certutil.log'
                If (-Not (Test-Path -Path $certLogFile)) {
                    New-Item -Path $certLogFile -ItemType File -Force
                }
                Add-Content -Path $certLogFile -Value "Certificate Service Restarted ..."
```

**Comment by PlagueHO** [comment]
Thanks @kungfu71186 - I'll do a big batch of fixes on Thursday night (snowed under the next two nights).

**Comment by PlagueHO** [comment]
This one is a little bit strange as `Add-Content` should actually create the file if it does not exist. However, it won't create the folder. Is it the folder that does not exist or the file itself? I agree about using the File resource to create the file though, but if it is the folder it is possibly easier to use the New-Item here. So I'll use that for now.

In the near term though I'd really like to get this resource completed as it removes the need for this: https://github.com/PowerShell/ActiveDirectoryCSDsc/issues/13

I might try and get that resource done this week if I can (only 3 years late).

**Comment by kungfu71186** [comment]
@PlagueHO yes, sorry, it's just the directory not being created. I may have some time this week to do a few things. Going to help close out AD, but those should be pretty quick and easy.

**Comment by PlagueHO** [comment]
I've done all of them except one now - also found some other issues I've fixed. Just need to do some testing by building the labs to make sure everything still working.
