### ISSUE TITLE
Install-Lab doesn't use default dsclibrary

### ISSUE THREAD

**Issue by DennisL68** [PlagueHO/LabBuilder#335]
PowerShell v5.1
PowerShell Console as Administrator
Windows 10 Pro (b18362)
LabBuilder v1.0.4.84

When using a labbuilder config from a custom location, Install-Lab assumes that DSCLibrary is present one level up from the configured labpath. 

```
New-LabException : The DSC Config file 'C:\Users\Public\Labs\.\..\DSCLibrary\DC_FORESTPRIMARY.DSC.ps1' specified in VM
'PoSH-Auto DC' could not be found.
At C:\Program Files\WindowsPowerShell\Modules\LabBuilder\1.0.4.84\LabBuilder.psm1:7179 char:21
+                     New-LabException @exceptionParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-LabException], Exception
    + FullyQualifiedErrorId : DSCConfigFileMissingError,New-LabException
```

This is easaly adjustable by setting dsclibrarypath.
But shouldn't the dsclibrary of the module always be used, at least by default (or as a fallback)?

The fallback path can always be found using different techniques
`split-path (get-module labbuilder).path`

**Comment by PlagueHO** [comment]
Great idea @DennisL68  - I'm implementing this now.

**Comment by PlagueHO** [comment]
This will also allow me to remove the dsclibrary path from all the samples.
