### ISSUE TITLE
Update Nano Server creation code to use Windows Server 2016 TP4 code

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#40]
Windows Server 2016 TP4 contains a PS Module for creating Nano Server images.

The conversion process for building Nano Server VHDx files should be adapted to use this module instead of using the DISM.EXE and other methods directly.

**Comment by DragonReach** [comment]
Hold off on this, TP5 or whatever it is going to be called should release in the near future if the previous release schedule holds.  Been about every 3 months and TP4 came out in Nov.

**Comment by PlagueHO** [comment]
Cool. I'll hold off on it. Would need to wait till your PR #39 is merged.

**Comment by DragonReach** [comment]
and I have no idea what else I can do to make that happen
I am reading docs on Git to see what I might have missed

**Comment by DragonReach** [comment]
Could also set to download latest convert-WindowsImage.PS1 from https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/master/hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.ps1

**Comment by PlagueHO** [comment]
Oh yes - definitely. Great idea!

I'll do some more work on this stuff later on tonight. I'm just finishing off the changes for issue #41

**Comment by PlagueHO** [comment]
This is now complete
