### ISSUE TITLE
Enable Guest Services for VMs

### ISSUE THREAD

**Issue by DragonReach** [PlagueHO/LabBuilder#41]
Option to enable the guest services Integration component or turn it on by default similar to enabling device naming

**Comment by PlagueHO** [comment]
Cool. I'll implement this.

**Comment by PlagueHO** [comment]
Given that there are (currently) 6 different integration services, it might be worth implementing as a generic "EnableIntegrationServices" node that can accept a comma delimited list of services to enable. E.g.
```xml
<EnableIntegrationServices>Guest Service Interface,Heartbeat,Key-Value Pair Exchange,Shutdown,Time Synchronization,VSS</EnableIntegrationServices>
```
If the EnableIntegrationServices isn't set for a VM then we just turn everything on (including Guest Service Interface). The Integration services are only enabled/disabled *if* the VM has the setting set.

In 99% of cases I'd think you'd want Guest Services enabled on all VM's anyway (at least on Windows VM's). Does this make sense?

**Comment by DragonReach** [comment]
Guest Services is the only one not enabled by default, simple check for enabled or not and flip if not works. Given that this enables the ability to use the copy-vmfile cmdlet which allows copying from host to VM without needing a network connection it is a valuable tool.
