### ISSUE TITLE
Unable to setup new-pssession due to untrusted host.

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#5]
Connecting to a remote host using PSRemoting either requires the host to be listed in the trusted hosts list **or** the connection to be made using HTTPS using SSL encryption. MSFT recommends using the later where possible.

Initially I was using PS Direct to connect directly to the VM's, but 10586 broke this functionality (it has been repaired in later releases, but Enterprise is still on 10586).

```Powershell
if (!((Get-Item WSMAN::localhost\Client\TrustedHosts) -eq "$IPAddress")) {set-item WSMAN::localhost\Client\TrustedHosts "$IPAddress" -Force}
                Write-Verbose "Included $IPAddress in TrustedHosts"
         Write-Verbose "Connecting to $IPAddress with $AdminCredential"
```

@DragonReach: What I propose is moving the PSSession connect code into a standalone function that all functions use to connect with. This will allow the connection method to be updated later once it is possible. I'm just working on this now.

**Comment by DragonReach** [comment]
Understand and agree,  Would much prefer using PSDirect

**Comment by PlagueHO** [comment]
Cool. I've implemented this now and tweaked the code a little to ensure that each VM IP address is added to the end of TrustedHosts if it isn't already in there. That way if someone already has TrustedHosts configured in some way the code won't break it.

I'll submit the PR momentarily.
