### ISSUE TITLE
Create Initialize-VHD Function

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#58]
Use:
```powershell
<#
.SYNOPSIS
    This function will determine if the mounted VHDx passed in DataPath is
    in a state that it can be written to.
    
    It checks that the disk has been paritioned and that it contains a volume
    that has been formatted.
    
    If the Fix switch is set it will fix the problems and put the disk into a
    state it can be written to.
#>
function Test-DiskWriteStatus
{
    [OutputType([Boolean])]
    [CmdletBinding()]
    Param (
        [String] $DiskPath,
        
        [Switch] $Fix,
        
        [String] $PartitionStyle = 'GPT',
        
        [String]
    )
    
    # Check partition style
    $DiskNumber = (Get-DiskImage -ImagePath $DiskPath).DiskNumber 
    if ((Get-Disk -Number $DiskNumber).PartitionStyle -eq 'RAW')
    {
        if ($Fix)
        {
            Initialize-Disk `
                -Number $DiskNumber `
                -PartitionStyle $PartitionStyle             
        }
        else
        {
            return $False
        }
    }
    
    # Check for a partition
    $Partitions = Get-Partition -DiskNumber $DiskNumber -ErrorAction SilentlyContinue
    if (-not ($Partitions))
    {
        if ($Fix)
        {
            
        }
        else
        {
            return $false
        }
    } 
    # Ok to write
    return $true
}
```

**Comment by PlagueHO** [comment]
@DragonReach - if the VHD already has more than one partition or more than one volume then this function will throw an error and not touch the drive. I though this is safer than trying to figure out which partition/volume to check/work with.

So basically the function will work just fine in these situations:
1. VHDx is not initialized.
2. VHDx is initialized but has 0 partitions
3. VHDx has 1 partition but 0 volumes
4. VHDx has 1 partition and 1 volume that is unformatted
5. VHDx has 1 partition and 1 volume that is formatted

Anything else and I'll have it intentionally throw an error and stop. Better that than do something it shouldn't to a data disk.

Also as part of this I'll add some additional attributes to the <datavhd> node to specify partition type and file system format. If either of these values are set the datavhd will be formatted **regardless** of whether or not you will be copying files to it. This will eliminate the need for using xStorage mostly - although a Drive letter will still need to be assigned I think.

Is this OK?

**Comment by PlagueHO** [comment]
I've added the first version of the function here:

https://github.com/PlagueHO/LabBuilder/blob/Issue-58-Add-Initialize-VHD-Function/LabBuilder/LabBuilder.psm1#L248

It is not finished or tested.

**Comment by DragonReach** [comment]
Might want to add a OS Ver check since ReFS is not available on client

**Comment by PlagueHO** [comment]
Very good point. Although ```Format-Volume``` will throw an exception saying this anyway and I've got the ```Format-Volume``` cmdlet set to stop if it happens. So no point raising our own version of the same error - it'll show up and terminate anyway.

**Comment by DragonReach** [comment]
Ok, I didn't catch that. and half my message didn't make it anyway  -
