### ISSUE TITLE
Add Support for Multiple Data disks to be specified for each VM

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LabBuilder#9]
As mentioned by @DragonReach

**Comment by DragonReach** [comment]
`      <DataVHDs>
        <DataVHD Exist="N"
                 Size="50GB"
                 Fixed="N"
                 SupportPR="N" />
        <DataVHD Exist="Y"
                 MoveOrCopy="Copy"
                 SourcePath=".\ToolsVHD\Tools.VHDX"
                 DestPath="\DataVHDs" />
      </DataVHDs>`

Basic idea for XML under <VM> tag  -- possibly be extending this as I think about it.

**Comment by PlagueHO** [comment]
So the above XML would:
1. Remove a 50GB fixed disk if it exists (should we specify a path? Don't want to remove/delete the wrong one)
2. Create a new data disk in the root of ?? in the folder \DataVhds that is a copy of .\ToolsVHD\Tools.vhdx (relative to the path of the configuration.xml file). 

If no destpath is specified then perhaps VHD would default to being put in the Virtual Hard Disks folder in the VM folder.

Question: What is the supportPR flag?

**Comment by DragonReach** [comment]
Nope, actually it is supposed to be two examples for the same VM

One creating a 50 GB VHDX
The Exist tag should be more of a Does it exist already piece.
The Fixed tag is to determine if it should be a fixed or dynamically expanding disk
SupportPR is short for the -supportpersistentreservation value used to create shared VHDX files

Yes, without a path, default to the Virtual Hard Disk Path for the VM

Second example is meant to either move or copy an existing VHDX to the specified directory under the VMs main directory (Just thinking options)

**Comment by PlagueHO** [comment]
So, to clarify:
if Exists = 'Y': Don't create the VHD - just attach it
if Exists = 'N': create the VHD with the options as specified.

I'm thinking we might not need that flag. We could use this:
To create a new 50GB Fixed VHDx with PR disabled in the D:\DataDisks\MyNewVHD.vhdx:
```xml
<DataVHD VHDPath="D:\DataDisks\MyNewVHD.vhdx" Size="50GB" Fixed="N" SupportPR="N"/>
```
To attach an existing VHDx that is in the D:\ToolsVHD\Tools.VHDX folder:
```xml
<DataVHD VHDPath="D:\ToolsVHD\Tools.VHDX">
```

To Copy (and rename) an existing Tools.vhdx found in the ToolsVHD folder to the D:\DataVHDs\SomenewTools.VHDx and attach it:
```xml
<DataVHD VHDPath="D:\DataVHDs\SomenewTools.VHDx" MoveOrCopy="Copy" SourcePath=".\ToolsVHD\Tools.VHDX" />
```

That way the VHDPath parameter is common to all parameter sets. This is also easier to code as there will just be 3 code paths.

Does that make sense to you and support your requirements?

**Comment by DragonReach** [comment]
Looks like it.  I was probably just overthinking it.

**Comment by PlagueHO** [comment]
Can always revisit it if we need to.

I'm mainly thinking of the VHDPath as a unique identifier that we can use to always ensure we're working with/on the correct disk. 

I'll see if I can get this working later on this afternoon.

**Comment by DragonReach** [comment]
Sounds good.

**Comment by PlagueHO** [comment]
I'm going to remove the Fixed='N' attrib and replace it with a Type attrib e.g.
```xml
<DataVHD VHDPath="D:\DataDisks\MyNewDynamicVHD.vhdx" Size="50GB" Type="Dyanmic" />
<DataVHD VHDPath="D:\DataDisks\MyNewFixedVHD.vhdx" Size="25GB" Type="Fixed" />
<DataVHD VHDPath="D:\ToolsVHD\Tools.VHDX">
<DataVHD VHDPath="D:\DataVHDs\SomenewTools.VHDx" MoveOrCopy="Copy" SourcePath=".\ToolsVHD\Tools.VHDX" />
<DataVHD VHDPath="D:\SharedVHD\Shared.VHDX" Type="Shared" Size="100GB" SupportPR="Y">
<DataVHD VHDPath="D:\DataVHDs\Differencing.VHDX" Type="Differencing" ParentVHD="D:\ParentDisk\Somedisk.vhdx">
```

The type attrib will be one of:
Fixed
Dynamic
Shared (will always create a Fixed disk)
Differencing

This will reduce the possibility of conflicting configs (e.g. trying to create a dynamic shared VHDx).

Ok with you?

**Comment by DragonReach** [comment]
Shared doesn’t have to be fixed size.

**Comment by PlagueHO** [comment]
Oh! I wonder why I thought it did? Or is it differencing that can't be a shared disk?

There goes that plan then :frowning: 

How about:
```xml
<DataVHD VHDPath="D:\DataDisks\MyNewDynamicVHD.vhdx" Size="50GB" Type="Dyanmic" /> 
<DataVHD VHDPath="D:\DataDisks\MyNewFixedVHD.vhdx" Size="25GB" Type="Fixed" />
<DataVHD VHDPath="D:\ToolsVHD\Tools.VHDX"> <DataVHD VHDPath="D:\DataVHDs\SomenewTools.VHDx" MoveOrCopy="Copy" SourcePath=".\ToolsVHD\Tools.VHDX" />
<DataVHD VHDPath="D:\SharedVHD\Shared.VHDX" Type="Dynamic" Size="100GB" Shared="Y" SupportPR="Y">
<DataVHD VHDPath="D:\DataVHDs\Differencing.VHDX" Type="Differencing" ParentVHD="D:\ParentDisk\Somedisk.vhdx"> 
```

**Comment by DragonReach** [comment]
I don’t think they can be differencing, but fixed or dynamic I know work fine.

**Comment by PlagueHO** [comment]
A possible future enhancement to this I may make as well is the ability to automatically mount the VHD to either a letter or path. This can already be done now via DSC, though so won't add it with this release - just something to keep in mind. Especially as things like partitioning and formatting come into play as well (all which can be currently done with DSC).

**Comment by PlagueHO** [comment]
Current task list to complete this item:
- [x] Update sample configuration files with <datavhds> structure and remove old datavhdsize attribute
- [x] Update Get-LabVMs to pull and validate <datavhds> structure from configuration xml.
- [ ] Update Unit tests for Get-LabVMs
- [ ] Create new function to create/update/manage data disk VHDs (separate from Initialize-LabVMs because function is getting too large).
