### ISSUE TITLE
Error on import-module.

### ISSUE THREAD

**Issue by DaveyRance** [PlagueHO/LabBuilder#92]
On a fresh 2016 TP4 server when running Import-Module Labbuilder from an elevated ISE the following error is thrown.

Import-LocalizedData : Cannot find the Windows PowerShell data file 'LabBuilder_LocalizedData.psd1' in directory 'C:\Program Files\WindowsPowerShell\Modules\LabBuilder\0.3.1.415\en-US\', or in any parent culture directories.
At C:\Program Files\WindowsPowerShell\Modules\LabBuilder\0.3.1.415\LabBuilder.psm1:10 char:1

The Module was installed using install-module Labbuilder 

Davey

**Comment by PlagueHO** [comment]
Unfortunately this build was released to PS Gallery by mistake - the automatic release code kicked in when it shouldn't. I'll fix the build and re-release it today. Sorry about that.

**Comment by PlagueHO** [comment]
I have pushed version 0.4.0.499 up onto PS Gallery and confirmed it isn't missing the en-us language file. So the error will be gone. Sorry about that and thanks for letter me know.

This project is still in pre-release but I am working hard to get it feature complete so that I can release 1.0.

**Comment by DaveyRance** [comment]
Works thank you.

**Comment by PlagueHO** [comment]
A pleasure :+1:
